-- 1. Przygotuj bazę danych --

CREATE TABLE Employees (
    employee_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name varchar(255),
    last_name varchar(255),
    email varchar(255),
    phone_number varchar(9),
    hire_date varchar(10),
    job_id int,
    salary float(20),
    commission_pct int,
    manager_id int,
    department_id int,
    PRIMARY KEY (employee_id)
);

CREATE TABLE Job_History (
    employee_id int,
    start_date varchar(10),
    end_date varchar(10),
    job_id int,
    department_id int
);

CREATE TABLE Jobs (
    job_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    job_title varchar(100),
    min_salary float(4),
    max_salary float(10),
    CONSTRAINT CHK_salary CHECK (max_salary - min_salary >= 2000)
);

CREATE TABLE Departments (
    department_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    department_name varchar(50),
    manager_id int,
    location_id int
);

CREATE TABLE Locations (
    location_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    street_address varchar(50),
    postal_code varchar(6),
    city varchar(50),
    state_province varchar(50),
    country_id int
);

CREATE TABLE Countries (
    country_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    country_name varchar(50),
    region_id int,
    PRIMARY KEY (country_id)
);

CREATE TABLE Regions (
    region_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    region_name varchar(50),
    PRIMARY KEY (region_id)
);

ALTER TABLE Jobs
ADD PRIMARY KEY (job_id);

ALTER TABLE Locations 
ADD PRIMARY KEY (location_id);

ALTER TABLE Departments
ADD PRIMARY KEY (department_id);

ALTER TABLE Job_History
ADD CONSTRAINT PK_Jobhistory PRIMARY KEY (employee_id, start_date);

ALTER TABLE Employees 
ADD CONSTRAINT FK_EmployeeManager
FOREIGN KEY (manager_id) REFERENCES Employees(employee_id);

ALTER TABLE Employees
ADD CONSTRAINT FK_EmployeeJob
FOREIGN KEY (job_id) REFERENCES Jobs(job_id);

ALTER TABLE Employees
ADD CONSTRAINT Fk_EmployeeDepartment
FOREIGN KEY (department_id) REFERENCES Departments(department_id);

ALTER TABLE Locations
ADD CONSTRAINT FK_LocationCountry
FOREIGN KEY (country_id) REFERENCES Countries(country_id);

ALTER TABLE Departments
ADD CONSTRAINT FK_ManagerDepartment
FOREIGN KEY (manager_id) REFERENCES Employees(employee_id);

ALTER TABLE Departments
ADD CONSTRAINT FK_LocationDepartment
FOREIGN KEY (location_id) REFERENCES Locations(location_id);

ALTER TABLE Job_History
ADD CONSTRAINT FK_JobhistoryEmployee
FOREIGN KEY (employee_id) REFERENCES Employees(employee_id);

ALTER TABLE Job_History
ADD CONSTRAINT FK_JobhistoryJob
FOREIGN KEY (job_id) REFERENCES Jobs(job_id);

ALTER TABLE Job_History
ADD CONSTRAINT FK_JobhistoryDepartment
FOREIGN KEY (department_id) REFERENCES Departments(department_id);

ALTER TABLE Countries 
ADD CONSTRAINT FK_CountryRegion
FOREIGN KEY (region_id) REFERENCES Regions(region_id);




