--------------------------------------------------------
--  File created - środa-marca-12-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "INF2S_FALKOWSKIE"."PRODUCTS" 
   (	"PRODUCT_ID" NUMBER, 
	"PRODUCT_NAME" VARCHAR2(40 BYTE), 
	"PRODUCT_CATEGORY" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into INF2S_FALKOWSKIE.PRODUCTS
SET DEFINE OFF;
Insert into INF2S_FALKOWSKIE.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRODUCT_CATEGORY) values ('1','roll','bakery products');
Insert into INF2S_FALKOWSKIE.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRODUCT_CATEGORY) values ('2','bread','bakery products');
Insert into INF2S_FALKOWSKIE.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRODUCT_CATEGORY) values ('3','donut','bakery products');
Insert into INF2S_FALKOWSKIE.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRODUCT_CATEGORY) values ('4','croissant','bakery products');
Insert into INF2S_FALKOWSKIE.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRODUCT_CATEGORY) values ('5','beef','meat');
Insert into INF2S_FALKOWSKIE.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRODUCT_CATEGORY) values ('6','chicken','meat');
Insert into INF2S_FALKOWSKIE.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRODUCT_CATEGORY) values ('7','pork','meat');
Insert into INF2S_FALKOWSKIE.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRODUCT_CATEGORY) values ('8','lamb','meat');
--------------------------------------------------------
--  DDL for Index PK_PRODUCT
--------------------------------------------------------

  CREATE UNIQUE INDEX "INF2S_FALKOWSKIE"."PK_PRODUCT" ON "INF2S_FALKOWSKIE"."PRODUCTS" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "INF2S_FALKOWSKIE"."PRODUCTS" ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
