--------------------------------------------------------
--  File created - środa-marca-12-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table JOB_HISTORY
--------------------------------------------------------

  CREATE TABLE "INF2S_FALKOWSKIE"."JOB_HISTORY" 
   (	"EMPLOYEE_ID" NUMBER(6,0), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"JOB_ID" VARCHAR2(10 BYTE), 
	"DEPARTMENT_ID" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into INF2S_FALKOWSKIE.JOB_HISTORY
SET DEFINE OFF;
Insert into INF2S_FALKOWSKIE.JOB_HISTORY (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values ('102',to_date('01/01/13','RR/MM/DD'),to_date('06/07/24','RR/MM/DD'),'IT_PROG','60');
Insert into INF2S_FALKOWSKIE.JOB_HISTORY (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values ('101',to_date('97/09/21','RR/MM/DD'),to_date('01/10/27','RR/MM/DD'),'AC_ACCOUNT','110');
Insert into INF2S_FALKOWSKIE.JOB_HISTORY (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values ('101',to_date('01/10/28','RR/MM/DD'),to_date('05/03/15','RR/MM/DD'),'AC_MGR','110');
Insert into INF2S_FALKOWSKIE.JOB_HISTORY (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values ('201',to_date('04/02/17','RR/MM/DD'),to_date('07/12/19','RR/MM/DD'),'MK_REP','20');
Insert into INF2S_FALKOWSKIE.JOB_HISTORY (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values ('114',to_date('06/03/24','RR/MM/DD'),to_date('07/12/31','RR/MM/DD'),'ST_CLERK','50');
Insert into INF2S_FALKOWSKIE.JOB_HISTORY (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values ('122',to_date('07/01/01','RR/MM/DD'),to_date('07/12/31','RR/MM/DD'),'ST_CLERK','50');
Insert into INF2S_FALKOWSKIE.JOB_HISTORY (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values ('200',to_date('95/09/17','RR/MM/DD'),to_date('01/06/17','RR/MM/DD'),'AD_ASST','90');
Insert into INF2S_FALKOWSKIE.JOB_HISTORY (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values ('176',to_date('06/03/24','RR/MM/DD'),to_date('06/12/31','RR/MM/DD'),'SA_REP','80');
Insert into INF2S_FALKOWSKIE.JOB_HISTORY (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values ('176',to_date('07/01/01','RR/MM/DD'),to_date('07/12/31','RR/MM/DD'),'SA_MAN','80');
Insert into INF2S_FALKOWSKIE.JOB_HISTORY (EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID,DEPARTMENT_ID) values ('200',to_date('02/07/01','RR/MM/DD'),to_date('06/12/31','RR/MM/DD'),'AC_ACCOUNT','90');
--------------------------------------------------------
--  DDL for Index PK_JOBHISTORY
--------------------------------------------------------

  CREATE UNIQUE INDEX "INF2S_FALKOWSKIE"."PK_JOBHISTORY" ON "INF2S_FALKOWSKIE"."JOB_HISTORY" ("EMPLOYEE_ID", "START_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table JOB_HISTORY
--------------------------------------------------------

  ALTER TABLE "INF2S_FALKOWSKIE"."JOB_HISTORY" ADD CONSTRAINT "CHK_DATE" CHECK (end_date > start_date) ENABLE;
  ALTER TABLE "INF2S_FALKOWSKIE"."JOB_HISTORY" ADD CONSTRAINT "PK_JOBHISTORY" PRIMARY KEY ("EMPLOYEE_ID", "START_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "INF2S_FALKOWSKIE"."JOB_HISTORY" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
  ALTER TABLE "INF2S_FALKOWSKIE"."JOB_HISTORY" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "INF2S_FALKOWSKIE"."JOB_HISTORY" MODIFY ("END_DATE" NOT NULL ENABLE);
  ALTER TABLE "INF2S_FALKOWSKIE"."JOB_HISTORY" MODIFY ("JOB_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table JOB_HISTORY
--------------------------------------------------------

  ALTER TABLE "INF2S_FALKOWSKIE"."JOB_HISTORY" ADD CONSTRAINT "FK_EMPLOYEEJOBHISTROY" FOREIGN KEY ("EMPLOYEE_ID")
	  REFERENCES "INF2S_FALKOWSKIE"."EMPLOYEES" ("EMPLOYEE_ID") ENABLE;
  ALTER TABLE "INF2S_FALKOWSKIE"."JOB_HISTORY" ADD CONSTRAINT "FK_JOBHISTORYDEPARTMENT" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "INF2S_FALKOWSKIE"."DEPARTMENTS" ("DEPARTMENT_ID") ENABLE;
  ALTER TABLE "INF2S_FALKOWSKIE"."JOB_HISTORY" ADD CONSTRAINT "FK_JOBJOBHISTORY" FOREIGN KEY ("JOB_ID")
	  REFERENCES "INF2S_FALKOWSKIE"."JOBS" ("JOB_ID") ENABLE;
