-- Kopiowanie tabel --

CREATE TABLE COUNTRIES AS 
SELECT * FROM HR.COUNTRIES;

CREATE TABLE DEPARTMENTS AS
SELECT * FROM HR.DEPARTMENTS;

CREATE TABLE EMPLOYEES AS
SELECT * FROM HR.EMPLOYEES;

CREATE TABLE JOB_GRADES AS
SELECT * FROM HR.JOB_GRADES;

CREATE TABLE JOB_HISTORY AS
SELECT * FROM HR.JOB_HISTORY;

CREATE TABLE JOBS AS
SELECT * FROM HR.JOBS;

CREATE TABLE LOCATIONS AS
SELECT * FROM HR.LOCATIONS;

CREATE TABLE PRODUCTS AS 
SELECT * FROM HR.PRODUCTS;

CREATE TABLE REGIONS AS
SELECT * FROM HR.REGIONS;

CREATE TABLE SALES AS
SELECT * FROM HR.SALES;
