--------------------------------------------------------
--  File created - środa-marca-12-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table JOB_GRADES
--------------------------------------------------------

  CREATE TABLE "INF2S_FALKOWSKIE"."JOB_GRADES" 
   (	"GRADE" CHAR(1 BYTE), 
	"MIN_SALARY" NUMBER(*,0), 
	"MAX_SALARY" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into INF2S_FALKOWSKIE.JOB_GRADES
SET DEFINE OFF;
Insert into INF2S_FALKOWSKIE.JOB_GRADES (GRADE,MIN_SALARY,MAX_SALARY) values ('A','0','2999');
Insert into INF2S_FALKOWSKIE.JOB_GRADES (GRADE,MIN_SALARY,MAX_SALARY) values ('B','3000','4999');
Insert into INF2S_FALKOWSKIE.JOB_GRADES (GRADE,MIN_SALARY,MAX_SALARY) values ('C','5000','7999');
Insert into INF2S_FALKOWSKIE.JOB_GRADES (GRADE,MIN_SALARY,MAX_SALARY) values ('D','8000','9999');
Insert into INF2S_FALKOWSKIE.JOB_GRADES (GRADE,MIN_SALARY,MAX_SALARY) values ('E','10000','14999');
Insert into INF2S_FALKOWSKIE.JOB_GRADES (GRADE,MIN_SALARY,MAX_SALARY) values ('F','15000','200999');
--------------------------------------------------------
--  DDL for Index PK_JOBGRADES
--------------------------------------------------------

  CREATE UNIQUE INDEX "INF2S_FALKOWSKIE"."PK_JOBGRADES" ON "INF2S_FALKOWSKIE"."JOB_GRADES" ("GRADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table JOB_GRADES
--------------------------------------------------------

  ALTER TABLE "INF2S_FALKOWSKIE"."JOB_GRADES" ADD CONSTRAINT "PK_JOBGRADES" PRIMARY KEY ("GRADE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
