--------------------------------------------------------
--  File created - środa-marca-12-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REGIONS
--------------------------------------------------------

  CREATE TABLE "INF2S_FALKOWSKIE"."REGIONS" 
   (	"REGION_ID" NUMBER, 
	"REGION_NAME" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into INF2S_FALKOWSKIE.REGIONS
SET DEFINE OFF;
Insert into INF2S_FALKOWSKIE.REGIONS (REGION_ID,REGION_NAME) values ('1','Europe');
Insert into INF2S_FALKOWSKIE.REGIONS (REGION_ID,REGION_NAME) values ('2','Americas');
Insert into INF2S_FALKOWSKIE.REGIONS (REGION_ID,REGION_NAME) values ('3','Asia');
Insert into INF2S_FALKOWSKIE.REGIONS (REGION_ID,REGION_NAME) values ('4','Middle East and Africa');
--------------------------------------------------------
--  DDL for Index FK_REGION
--------------------------------------------------------

  CREATE UNIQUE INDEX "INF2S_FALKOWSKIE"."FK_REGION" ON "INF2S_FALKOWSKIE"."REGIONS" ("REGION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table REGIONS
--------------------------------------------------------

  ALTER TABLE "INF2S_FALKOWSKIE"."REGIONS" ADD CONSTRAINT "PK_REGION" PRIMARY KEY ("REGION_ID")
  USING INDEX (CREATE UNIQUE INDEX "INF2S_FALKOWSKIE"."FK_REGION" ON "INF2S_FALKOWSKIE"."REGIONS" ("REGION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "INF2S_FALKOWSKIE"."REGIONS" MODIFY ("REGION_ID" NOT NULL ENABLE);
